spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecommerce?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app
    password: app123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
    root: info
server:
  port: 18082